In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("fatihilhan/global-superstore-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/fatihilhan/global-superstore-dataset/1.archive...

100%|██████████| 3.19M/3.19M [00:00<00:00, 4.99MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/fatihilhan/global-superstore-dataset/versions/1

In [2]:
!ls /root/.cache/kagglehub/datasets/fatihilhan/global-superstore-dataset/versions/1

superstore.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(f"{path}/superstore.csv")

In [5]:
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [6]:
df.value_counts("Country")

Country
United States    9994
Australia        2837
France           2827
Mexico           2644
Germany          2065
                 ...
Eritrea             2
Burundi             2
Chad                2
South Sudan         2
Swaziland           2
Name: count, Length: 147, dtype: int64